# Generated by Django 3.2.8 on 2021-12-05 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('Credential', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pd_credential',
            },
        ),
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('drugid', models.IntegerField(default=0)),
                ('drugname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('isopioid', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'pd_drugs',
            },
        ),
        migrations.CreateModel(
            name='Prescriber',
            fields=[
                ('NPI', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=25)),
                ('Lname', models.CharField(max_length=25)),
                ('Gender', models.CharField(max_length=1)),
                ('Credential', models.CharField(max_length=25)),
                ('Specialty', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pd_prescriber',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state', models.CharField(max_length=30)),
                ('stateabbrev', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('population', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'pd_statedata',
            },
        ),
        migrations.CreateModel(
            name='Triple',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('qty', models.IntegerField(default=0)),
                ('drugname', models.ForeignKey(db_column='drugname', default='', on_delete=django.db.models.deletion.DO_NOTHING, to='drugsApp.drugs')),
                ('prescriberid', models.ForeignKey(db_column='prescriberid', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='drugsApp.prescriber')),
            ],
            options={
                'db_table': 'pd_triple',
            },
        ),
        migrations.AddField(
            model_name='prescriber',
            name='StateAbbreviation',
            field=models.ForeignKey(db_column='StateAbbreviation', default='', max_length=2, on_delete=django.db.models.deletion.DO_NOTHING, to='drugsApp.state'),
        ),
    ]
