# Generated by Django 3.2.8 on 2021-12-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugsApp', '0002_auto_20211204_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('Specialty', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pd_specialty',
            },
        ),
        migrations.AddField(
            model_name='drugs',
            name='average',
            field=models.IntegerField(default=0),
        ),
    ]
