# Generated by Django 3.2.8 on 2021-12-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugsApp', '0003_auto_20211206_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriber',
            name='IsOpioidPrescriber',
            field=models.CharField(max_length=5),
        ),
    ]
